<?php

/**
 * @file
 * Provides an flat rate shipping method for Drupal Commerce for testing and
 * development.
 */

/**
 * Implementation of hook_ctools_plugin_directory().
 */
function commerce_shipping_flat_rate_ctools_plugin_directory($owner, $plugin_type) {
  // Standard ctools hook, used to tell ctools where our commerce shipping
  // plugins are located.
  if ($owner == 'commerce_shipping') {
    return "plugins/$plugin_type";
  }
}
